fixtures:
  symlinks:
    pixelated: "#{source_dir}"
    site_apt: "#{source_dir}/../site_apt"
    site_sshd: "#{source_dir}/../site_sshd"
    haveged: "#{source_dir}/../haveged"
    site_check_mk: "#{source_dir}/../site_check_mk"
    site_shorewall: "#{source_dir}/../site_shorewall"
    site_postfix: "#{source_dir}/../site_postfix"
    augeas:    "#{source_dir}/../augeas"
    check_mk:    "#{source_dir}/../check_mk"
  repositories:
    stdlib:    " https://leap.se/git/puppet_stdlib"
    apt:       "https://leap.se/git/puppet_apt"
    lsb:       "https://leap.se/git/puppet_lsb"
    git:       "https://leap.se/git/puppet_git"
    sysctl:    "https://leap.se/git/puppet_sysctl"
    shorewall: "https://leap.se/git/puppet_shorewall"
    sshd:      "https://leap.se/git/puppet_sshd"
    resolvconf: "https://leap.se/git/puppet_resolvconf.git"
    unbound:   "https://leap.se/git/puppet_unbound"
    concat:    "https://leap.se/git/puppet_concat"
    rsyslog:   "https://leap.se/git/puppet_rsyslog"
    vcsrepo:   "https://leap.se/git/puppet_vcsrepo"
    postfix:   "https://leap.se/git/puppet_postfix"
    common:    "https://leap.se/git/puppet_common"
    x509:      "https://leap.se/git/puppet_x509"
